extends:
  - 'eslint:recommended'
  - 'prettier'
parserOptions:
  sourceType: 'module'
env:
  browser: true
  es6: true
overrides:
  - files:
      - jest.config.js
    env:
      node: true
  - files: '*.vue'
    extends:
      - 'plugin:vue/vue3-recommended'
    parser: 'vue-eslint-parser'
    rules:
      # TODO: fix names
      vue/multi-word-component-names: 'off'
  - files: '*.ts'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      parser: '@typescript-eslint/parser'
      project:
        - './tsconfig.json'
      extraFileExtensions:
        - '.vue'
      sourceType: 'module'
    plugins:
      - '@typescript-eslint'
  - files: 'src/components/PieceOnBoard.vue'
    extends:
      - 'plugin:vue/vue3-recommended'
      - 'plugin:@typescript-eslint/recommended'
    parser: 'vue-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      project:
        - './tsconfig.json'
      extraFileExtensions:
        - '.vue'
    rules:
      # TODO: fix names
      vue/multi-word-component-names: 'off'
  - files: '*.{test,spec}.{js,ts}'
    env:
      jest/globals: true
    plugins:
      - 'jest'
    rules:
      jest/no-disabled-tests: warn
      jest/no-focused-tests: error
      jest/no-identical-title: error
      jest/prefer-to-have-length: warn
      jest/valid-expect: error
